const PDFDocument = require('pdfkit');
const fs = require('fs');
const path = require('path');
const Rfq = require('../models/Rfq');
const { ensureDir } = require('../utils/fileHelper');
const config = require('../config');

/**
 * Export an RFQ to PDF file.
 * Note: Chinese character support requires a font file. This implementation
 * uses PDFKit's built-in Helvetica for ASCII and adds a note about CJK fonts.
 *
 * @param {string} rfqId
 * @returns {Promise<string>} File path of the generated PDF file
 */
async function exportRfq(rfqId) {
  const rfq = await Rfq.findById(rfqId);
  if (!rfq) {
    throw new Error('RFQ not found.');
  }

  const exportDir = ensureDir(config.upload.exportDir);
  const filename = `rfq_${rfqId.substring(0, 8)}_${Date.now()}.pdf`;
  const filePath = path.join(exportDir, filename);

  const doc = new PDFDocument({
    size: 'A4',
    margin: 50,
    info: {
      Title: rfq.title,
      Author: 'RFQ Tool',
      Subject: '询价单',
      CreationDate: new Date(),
    },
  });

  const stream = fs.createWriteStream(filePath);
  doc.pipe(stream);

  // ---------- Title ----------
  doc.fontSize(20).text(rfq.title, { align: 'center' });
  doc.moveDown(0.5);

  // ---------- Info line ----------
  doc.fontSize(10).fillColor('#666666');
  doc.text(
    `Status: ${rfq.status}  |  Date: ${new Date(rfq.created_at).toLocaleDateString('zh-CN')}  |  Items: ${rfq.items.length}`,
    { align: 'center' }
  );
  doc.moveDown(1);
  doc.fillColor('#000000');

  // ---------- Table header ----------
  const tableTop = doc.y;
  const columns = [
    { header: 'Product Name', x: 50, width: 130 },
    { header: 'Spec', x: 180, width: 80 },
    { header: 'Qty', x: 260, width: 45 },
    { header: 'Unit', x: 305, width: 40 },
    { header: 'Target Price', x: 345, width: 65 },
    { header: 'Delivery', x: 410, width: 65 },
    { header: 'Remarks', x: 475, width: 70 },
  ];

  drawTableHeader(doc, columns, tableTop);
  doc.moveDown(0.5);

  // ---------- Table rows ----------
  let y = doc.y;
  rfq.items.forEach((item, index) => {
    // Check if we need a new page
    if (y > 700) {
      doc.addPage();
      y = 50;
      drawTableHeader(doc, columns, y);
      y += 25;
    }

    const rowData = [
      item.product_name,
      item.specification || '',
      String(item.quantity),
      item.unit,
      item.target_price ? `¥${item.target_price}` : '',
      item.delivery_date || '',
      item.remarks || '',
    ];

    doc.fontSize(9).fillColor('#333333');
    columns.forEach((col, i) => {
      doc.text(rowData[i] || '', col.x, y, {
        width: col.width - 5,
        ellipsis: true,
      });
    });

    // Draw row separator
    doc.moveTo(50, y + 18)
      .lineTo(545, y + 18)
      .strokeColor('#E0E0E0')
      .stroke();

    y += 22;
  });

  // ---------- Supplier section ----------
  if (rfq.suppliers && rfq.suppliers.length > 0) {
    if (y > 600) {
      doc.addPage();
      y = 50;
    } else {
      y += 20;
    }

    doc.fontSize(14).fillColor('#000000').text('Supplier Responses', 50, y);
    y += 25;

    rfq.suppliers.forEach((sup) => {
      if (y > 700) {
        doc.addPage();
        y = 50;
      }

      doc.fontSize(10).fillColor('#333333');
      doc.text(`${sup.supplier_name}`, 50, y);
      doc.text(`Contact: ${sup.supplier_contact_person || 'N/A'}`, 250, y);
      doc.text(`Responded: ${sup.responded ? 'Yes' : 'No'}`, 400, y);
      if (sup.quote_amount) {
        y += 15;
        doc.text(`Quote: ¥${sup.quote_amount}`, 50, y);
        if (sup.quote_notes) {
          doc.text(`Notes: ${sup.quote_notes}`, 250, y, { width: 250, ellipsis: true });
        }
      }
      y += 25;
    });
  }

  // ---------- Footer ----------
  doc.fontSize(8).fillColor('#999999');
  const bottomY = doc.page.height - 50;
  doc.text(
    `Generated by RFQ Tool  |  ${new Date().toISOString()}`,
    50,
    bottomY,
    { align: 'center' }
  );

  doc.end();

  return new Promise((resolve, reject) => {
    stream.on('finish', () => resolve(filePath));
    stream.on('error', reject);
  });
}

function drawTableHeader(doc, columns, y) {
  const headerHeight = 22;
  doc.rect(50, y, 495, headerHeight)
    .fillColor('#E0E0E0')
    .fill();
  doc.fillColor('#000000');

  doc.fontSize(9).font('Helvetica-Bold');
  columns.forEach(col => {
    doc.text(col.header, col.x, y + 5, { width: col.width - 5 });
  });
  doc.font('Helvetica');
}

module.exports = { exportRfq };
